fotoblog/fotoblog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from authentication import views as av # av for authenticationviews
from blog import views as bv # bv for blogviews
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', av.registering_page, name="register"),
    # path('register/', av.RegisteringPageView.as_view(), name="register"),
    # path('', av.LoginPageView.as_view(), name="login"),
    path('logout/', av.logout_user, name="logout"),
    path(
        '',
        LoginView.as_view(
            template_name = "authentication/login.html",
            redirect_authenticated_user = True
        ),
        name="login"
    ),
    # path('logout/', LogoutView.as_view(), name="logout"),
    path(
        'password/change/',
        PasswordChangeView.as_view(
            template_name = "authentication/password_update.html"
        ),
        name="password_change"
    ),
    path(
        'password/change/done/',
        PasswordChangeDoneView.as_view(
            template_name = "authentication/password_change_done.html"
        ),
        name="password_change_done"
    ),
    path("profile_photo/change/", av.change_profile_photo, name="pp_update"),
    path('accueil/', bv.accueil, name="accueil"),
    path("photo/upload/", bv.photo_upload, name="photo_upload"),
    path('photo/upload-multiple/', bv.create_multiple_photos, name='create_multiple_photos'),
    path('photo/feed/', bv.photo_feed, name='photo_feed'),
    path("blog/creation/", bv.blog_creation, name="blog_creation"),
    path("blog/read/<int:blog_id>/", bv.view_blog, name="view_blog"),
    path('blog/edit/<int:blog_id>/', bv.edit_blog, name='edit_blog'),
    path('about-us/', bv.about_us, name="about_us"),
    path('contact-us/', bv.contact_us, name="contact_us"),
    path('follow-users/', bv.follow_users, name='follow_users'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

fotoblog/blog/models.py
from PIL import Image
from django.conf import settings
from django.db import models

# Create your models here.
class Photo(models.Model):
    image = models.ImageField()
    caption = models.CharField(max_length=128, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add = True)

    IMAGE_MAX_SIZE = (800, 800)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        # sauvegarde de l’image redimensionnée dans le système de fichiers
        # ce n’est pas la méthode save() du modèle !
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()


class Blog(models.Model):
    photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128)
    content = models.CharField(max_length=5000)
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    word_count = models.IntegerField(null=True)
    contributors = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through="BlogContributor",
        related_name="contributions"
    )

    def _get_word_count(self):
        mots = self.content.split(" ")
        return len(mots)
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.word_count = self._get_word_count()

class BlogContributor(models.Model):
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contribution = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ("contributor", "blog")

fotoblog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/favicon.png' %}" type="image/x-icon">
    <title>FotoBlog</title>
</head>
<body>
    <header>
        <nav>
            
        </nav>
    </header>
    <aside class="sidebar">
        <h1>FotoBlog</h1>
        {% if user.is_authenticated %}
            <p>Salut, {{ user }} !</p>
            {% if user.profile_photo %}
                <img class="avatar" src={{ user.profile_photo.url }}>
            {% else %}
                <img class="avatar" src="{% static 'assets/default_profile.png'%}">
            {% endif %}
            <p><a href="{% url 'accueil' %}">Accueil</a></p>
            <p><a href="{% url 'photo_feed' %}">Photos</a></p>
            {% if perms.blog.add_photo %}
                {% if perms.blog.add_blog %}
                    <p><a href="{% url 'blog_creation' %}">Ecrire un billet</a></p>
                {% endif %}
                <p><a href="{% url 'photo_upload' %}">Téléverser une photo</a></p>
                <p><a href="{% url 'create_multiple_photos' %}">Télécharger plusieurs photos</a></p>
            {% endif %}
            <p><a href="{% url 'follow_users' %}">Suivre des utilisateurs</a></p>
            <p><a href="{% url 'pp_update' %}">Changer la photo de profil</a></p>
            <p><a href="{% url 'password_change' %}">Changer le mot de passe</a></p>
            <!-- <p><a href="{% url 'about_us' %}">About us</a></p>
            <p><a href="{% url 'contact_us' %}">Contact us</a></p> -->
            <p><a href="{% url 'logout' %}">Se déconnecter</a></p>
        {% else %}
            <p><a href="{% url 'register' %}">Register</a></p>
            <p><a href="{% url 'login' %}">Login</a></p>
        {% endif %}
    </aside>
    <main class="main">
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        {% if user.is_authenticated %}
            <div class="connected_user">
                <p>
                    Vous êtes connecté en tant que {{ request.user }}. <a href="{% url 'logout' %}">Se déconnecter</a>
                </p>
            </div>
        {% endif %}
        <div class="copyright">
            <p>
                &copy; 2024 <br/>
                Created by <a href="https://www.linkedin.com/in/yao-david-soussoukpo-0a52a222a/" target="_blank" rel="noopener">Yao David SOUSSOUKPO</a>
            </p>
        </div>
    </footer>
</body>
</html>